In [2]:
import pandas as pd

In [3]:
df = pd.read_excel("WHR25_Data_Figure_2.1.xlsx")
df

,Year,Rank,Country name,Ladder score,upperwhisker,lowerwhisker,Explained by: Log GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption,Dystopia + residual
0,2024,1,Finland,7.736,7.810,7.662,1.749,1.783,0.824,0.986,0.110,0.502,1.782
1,2023,143,Afghanistan,1.721,1.775,1.667,0.628,0.000,0.242,0.000,0.091,0.088,0.672
2,2022,137,Afghanistan,1.859,1.923,1.795,0.645,0.000,0.087,0.000,0.093,0.059,0.976
3,2021,146,Afghanistan,2.404,2.469,2.339,0.758,0.000,0.289,0.000,0.089,0.005,1.263
4,2020,150,Afghanistan,2.523,2.596,2.449,0.370,0.000,0.126,0.000,0.122,0.010,1.895
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1964,2016,138,Zimbabwe,3.875,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1965,2015,131,Zimbabwe,4.193,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1966,2014,115,Zimbabwe,4.610,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1967,2012,103,Zimbabwe,4.827,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1968,2011,142,Zimbabwe,3.978,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
df_2024 = df[df["Year"] == 2024].sort_values(by="Rank")
df_2024[:10][["Country name", "Rank"]].to_dict()

{'Country name': {0: 'Finland',
  13: 'Denmark',
  26: 'Iceland',
  45: 'Sweden',
  58: 'Netherlands',
  71: 'Costa Rica',
  84: 'Norway',
  97: 'Israel',
  109: 'Luxembourg',
  122: 'Mexico'},
 'Rank': {0: 1,
  13: 2,
  26: 3,
  45: 4,
  58: 5,
  71: 6,
  84: 7,
  97: 8,
  109: 9,
  122: 10}}

In [5]:
df_2024[["Country name", "Ladder score"]]

      Country name  Ladder score
0          Finland         7.736
13         Denmark         7.521
26         Iceland         7.515
45          Sweden         7.345
58     Netherlands         7.306
...            ...           ...
1905      Zimbabwe         3.396
1918        Malawi         3.260
1931       Lebanon         3.188
1943  Sierra Leone         2.998
1956   Afghanistan         1.364

[147 rows x 2 columns]

In [21]:
df[~(df["Country name"] == "Colombia")].sort_values(by="Year").groupby(by="Year").agg({"Ladder score": "mean", "Rank": "mean"}).to_dict()

{'Ladder score': {2011: 5.386309677419355,
  2012: 5.412296774193548,
  2014: 5.368726114649681,
  2015: 5.375141025641026,
  2016: 5.3475064935064935,
  2017: 5.370174193548387,
  2018: 5.402464516129032,
  2019: 5.468699334483397,
  2020: 5.529601351351351,
  2021: 5.552006896551724,
  2022: 5.539132352941176,
  2023: 5.526401408450704,
  2024: 5.575253424657534},
 'Rank': {2011: 78.74193548387096,
  2012: 78.78064516129032,
  2014: 79.79617834394904,
  2015: 79.3076923076923,
  2016: 78.27272727272727,
  2017: 78.76774193548387,
  2018: 78.66451612903226,
  2019: 77.21710526315789,
  2020: 76.1554054054054,
  2021: 73.55172413793103,
  2022: 68.9779411764706,
  2023: 71.95774647887323,
  2024: 74.08904109589041}}